# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#
#  Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:b m cm NH
  push:
    branches: [ "main" ]
  workflow_dispatch:

cb m v I GJ in by him by
